name: Setup
description: Setup Rust and Deno environment.

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain (nightly)
      shell: bash
      run: |
        rustup toolchain install nightly --profile minimal
        rustup default nightly
        rustup component add clippy rustfmt
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
