[package]
name = "vm"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
foundation.workspace = true
anyhow = { workspace = true }
bitflags = { workspace = true }
