[package]
name = "run"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lexer.workspace = true
parser.workspace = true
compiler.workspace = true
vm.workspace = true
