[workspace]
resolver = "2"
members = [
    "foundation",
]

[workspace.package]
version = "0.3.0"
authors = ["ryota2357"]
edition = "2021"

[workspace.dependencies]
foundation.path = "./foundation/"

[package]
name = "lico_core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
foundation.workspace = true
