[package]
name = "compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
parser.workspace = true
lexer.workspace = true
vm.workspace = true
rustc-hash = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
