[package]
name = "parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
foundation.workspace = true
rowan = { workspace = true }

[dev-dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
