[package]
name = "lexer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
foundation.workspace = true
thiserror = { workspace = true }
unicode-ident = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
