warmup = 1
runs = 10

[[benches]]
name = "Lua"
base = true
command = "lua"
path = "main.lua"

[[benches]]
name = "Lico"
command = "lico run"
path = "main.lico"

[[benches]]
name = "Python"
command = "python"
path = "main.py"
