name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: ructions/toolchain@v2
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Format
        run: make format

      - name: Check
        run: make check

      - name: Test
        run: make test
