name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/

      - name: Format
        run: make format

      - name: Check
        run: make check

  test-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/

      - name: Test (cargo)
        run: |
          cargo test --manifest-path ./src/Cargo.toml --workspace
          cargo test --manifest-path ./cli/Cargo.toml --workspace

      - name: Test
        run: cd ./tests/ && deno task test debug

  test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/

      - name: Test (cargo)
        run: |
          cargo test --manifest-path ./src/Cargo.toml --workspace --release
          cargo test --manifest-path ./cli/Cargo.toml --workspace --release

      - name: Test
        run: cd ./tests/ && deno task test release
